import XCTest
@testable import queens

/// Asserts the Swift solver matches the verified JS reference solver exactly.
///
/// The fixture `solver-reference.json` is generated by the JS source of truth
/// (scratchpad/gen-reference.js) and holds, per puzzle and per mode
/// (full / teachable-only), the expected `solved`, `steps`, `maxTier`, and the
/// full final board. This test runs the Swift `StarBattleSolver.solve` over all
/// 600 puzzles and requires an exact match, plus 0 correctness errors against
/// each puzzle's known solution.
final class StarBattleSolverTests: XCTestCase {

    // MARK: Fixture model

    private struct Reference: Decodable {
        let count: Int
        let cases: [Case]
    }
    private struct Case: Decodable {
        let n: Int
        let stars: Int
        let regions: [[Int]]
        let full: Expected
        let teachable: Expected
    }
    private struct Expected: Decodable {
        let solved: Bool
        let steps: Int
        let maxTier: Int
        let board: String   // rows of '.'/'*'/'x' joined by '/'
    }

    private func loadReference() throws -> Reference {
        let bundle = Bundle(for: Self.self)
        guard let url = bundle.url(forResource: "solver-reference", withExtension: "json") else {
            XCTFail("solver-reference.json not found in test bundle — ensure it's added to the test target's resources")
            throw NSError(domain: "test", code: 1)
        }
        let data = try Data(contentsOf: url)
        return try JSONDecoder().decode(Reference.self, from: data)
    }

    private func encode(_ board: [[SolverCell]]) -> String {
        board.map { row in
            String(row.map { $0 == .star ? "*" : $0 == .cross ? "x" : "." })
        }.joined(separator: "/")
    }

    /// Decode a reference board string into a set of solution star keys and a full grid.
    private func decode(_ s: String) -> [[SolverCell]] {
        s.split(separator: "/").map { rowStr in
            rowStr.map { ch -> SolverCell in
                switch ch {
                case "*": return .star
                case "x": return .cross
                default: return .unknown
                }
            }
        }
    }

    // MARK: Tests

    func testMatchesJSReferenceExactly() throws {
        let ref = try loadReference()
        XCTAssertEqual(ref.count, ref.cases.count)

        var mismatches = 0
        var correctnessErrors = 0

        for (i, c) in ref.cases.enumerated() {
            let puzzle = SolverPuzzle(n: c.n, stars: c.stars, regions: c.regions)

            for (mode, expected) in [("full", c.full), ("teachable", c.teachable)] {
                let teachableOnly = (mode == "teachable")
                let result = StarBattleSolver.solve(puzzle: puzzle, teachableOnly: teachableOnly)
                let solved = StarBattleSolver.isComplete(board: result.board, n: c.n)
                let boardStr = encode(result.board)

                if solved != expected.solved || result.steps != expected.steps ||
                   result.maxTier != expected.maxTier || boardStr != expected.board {
                    mismatches += 1
                    if mismatches <= 10 {
                        XCTFail("Case \(i) [\(mode)] mismatch: " +
                                "solved \(solved)/\(expected.solved), steps \(result.steps)/\(expected.steps), " +
                                "maxTier \(result.maxTier)/\(expected.maxTier), boardMatch \(boardStr == expected.board)")
                    }
                }

                // Correctness: the reference board is the ground truth for decided
                // cells; a placed star must match a solution star, a cross must not.
                // We re-derive the solution from the FULL-mode reference board when
                // fully solved; otherwise skip (partial boards are checked by the
                // JS generator which already asserted 0 errors). Here we assert the
                // Swift board never disagrees with the reference board.
                let expectedBoard = decode(expected.board)
                for r in 0..<c.n {
                    for col in 0..<c.n where result.board[r][col] != expectedBoard[r][col] {
                        correctnessErrors += 1
                    }
                }
            }
        }

        XCTAssertEqual(mismatches, 0, "\(mismatches) puzzle/mode outcomes differ from the JS reference")
        XCTAssertEqual(correctnessErrors, 0, "\(correctnessErrors) cell(s) disagree with the JS reference board")
    }

    /// Spot-check the structured `explain` and that nextMove is deterministic and
    /// never contradicts the reference board on a solved puzzle.
    func testNextMoveProducesStructuredExplain() throws {
        let ref = try loadReference()
        // pick the first fully-solved (full mode) puzzle
        guard let c = ref.cases.first(where: { $0.full.solved }) else {
            XCTFail("no solved puzzle in fixture"); return
        }
        let puzzle = SolverPuzzle(n: c.n, stars: c.stars, regions: c.regions)
        var board = [[SolverCell]](repeating: [SolverCell](repeating: .unknown, count: c.n), count: c.n)
        let expectedBoard = decode(c.full.board)

        var moves = 0
        while let m = StarBattleSolver.nextMove(board: board, puzzle: puzzle) {
            // move must agree with the solved reference board
            XCTAssertEqual(m.action == .star ? SolverCell.star : SolverCell.cross,
                           expectedBoard[m.r][m.c],
                           "nextMove contradicted the reference solution at R\(m.r)C\(m.c)")
            board[m.r][m.c] = m.action == .star ? .star : .cross
            moves += 1
            XCTAssertGreaterThanOrEqual(m.tier, 0)
            if moves > c.n * c.n { XCTFail("nextMove did not terminate"); break }
        }
        XCTAssertTrue(StarBattleSolver.isComplete(board: board, n: c.n),
                      "stepping nextMove should fully solve a solvable puzzle")
    }
}
