export const ADJECTIVES = [
  'Happy', 'Silly', 'Clever', 'Brave', 'Gentle',
  'Cheerful', 'Bright', 'Swift', 'Proud', 'Quiet',
  'Mighty', 'Tiny', 'Bouncy', 'Fuzzy', 'Sparkly',
  'Jolly', 'Lucky', 'Merry', 'Snappy', 'Sunny',
  'Zippy', 'Chipper', 'Daring', 'Eager', 'Fancy',
  'Giddy', 'Heroic', 'Jazzy', 'Keen', 'Lively',
  'Noble', 'Perky', 'Quick', 'Radiant', 'Spry',
  'Tidy', 'Upbeat', 'Vivid', 'Witty', 'Excited',
  'Friendly', 'Graceful', 'Helpful', 'Joyful', 'Playful',
  'Peaceful', 'Curious', 'Cozy', 'Dreamy', 'Peppy',
  'Adorable', 'Amazing', 'Awesome', 'Beaming', 'Bold',
  'Bubbly', 'Calm', 'Candid', 'Carefree', 'Charming',
  'Chilly', 'Colossal', 'Cosmic', 'Courageous', 'Cuddly',
  'Dazzling', 'Delightful', 'Devoted', 'Doting', 'Earnest',
  'Elegant', 'Energetic', 'Enormous', 'Fabulous', 'Fair',
  'Fearless', 'Festive', 'Fluffy', 'Flying', 'Focused',
  'Fond', 'Frank', 'Frisky', 'Frosty', 'Gallant',
  'Gigantic', 'Glowing', 'Golden', 'Grand', 'Grateful',
  'Groovy', 'Grounded', 'Humble', 'Hushed', 'Icy',
  'Imaginative', 'Inventive', 'Kind', 'Laughing', 'Limber',
  'Lovely', 'Loyal', 'Magical', 'Majestic', 'Mellow',
  'Mindful', 'Nimble', 'Optimistic', 'Outgoing', 'Patient',
  'Pensive', 'Petite', 'Plucky', 'Polite', 'Posh',
  'Precious', 'Prompt', 'Punchy', 'Pure', 'Quirky',
  'Regal', 'Reliable', 'Resourceful', 'Rosy', 'Rugged',
  'Sage', 'Serene', 'Sharp', 'Shiny', 'Shy',
  'Sincere', 'Sleek', 'Smiley', 'Smooth', 'Snazzy',
  'Soft', 'Sparkling', 'Speedy', 'Spirited', 'Splendid',
  'Sprightly', 'Stately', 'Steadfast', 'Stellar', 'Stoic',
  'Stout', 'Strong', 'Sturdy', 'Suave', 'Super',
  'Tender', 'Thankful', 'Thoughtful', 'Thriving', 'Timid',
  'Trusting', 'Truthful', 'Vibrant', 'Vigilant', 'Warm',
  'Whimsical', 'Wholesome', 'Wise', 'Wondrous', 'Zany',
  'Zesty', 'Zealous', 'Affectionate', 'Agile', 'Alert',
  'Amiable', 'Angelic', 'Animated', 'Artful', 'Assured',
  'Attentive', 'Balanced', 'Blissful', 'Blooming', 'Breezy',
  'Buoyant', 'Capable', 'Cheerio', 'Dashing', 'Dauntless',
  'Diligent', 'Dreaming', 'Enlivened', 'Effervescent', 'Elated',
  'Endearing', 'Exceptional', 'Exuberant', 'Feisty', 'Felicitous',
  'Genuine', 'Giving', 'Gleaming', 'Glorious', 'Gracious',
]

export const ANIMALS = [
  'Owl', 'Fox', 'Bear', 'Deer', 'Rabbit',
  'Otter', 'Panda', 'Koala', 'Penguin', 'Dolphin',
  'Butterfly', 'Hummingbird', 'Squirrel', 'Hedgehog', 'Swan',
  'Tiger', 'Lion', 'Elephant', 'Giraffe', 'Zebra',
  'Kangaroo', 'Monkey', 'Parrot', 'Turtle', 'Whale',
  'Eagle', 'Hawk', 'Robin', 'Sparrow', 'Finch',
  'Chipmunk', 'Raccoon', 'Badger', 'Beaver', 'Moose',
  'Wolf', 'Lynx', 'Jaguar', 'Cheetah', 'Leopard',
  'Seal', 'Walrus', 'Puffin', 'Flamingo', 'Peacock',
  'Mouse', 'Hamster', 'Guinea Pig', 'Ferret', 'Chinchilla',
  'Albatross', 'Alligator', 'Alpaca', 'Antelope', 'Armadillo',
  'Axolotl', 'Baboon', 'Bat', 'Bison', 'Bluebird',
  'Buffalo', 'Bullfrog', 'Bumblebee', 'Camel', 'Canary',
  'Capybara', 'Cardinal', 'Cassowary', 'Cat', 'Caterpillar',
  'Chameleon', 'Clownfish', 'Cockatoo', 'Crab', 'Crane',
  'Cricket', 'Crocodile', 'Crow', 'Cuckoo', 'Dingo',
  'Donkey', 'Dove', 'Dragonfly', 'Duck', 'Dugong',
  'Echidna', 'Falcon', 'Firefly', 'Frog', 'Gazelle',
  'Gecko', 'Gibbon', 'Goat', 'Goldfish', 'Goose',
  'Gorilla', 'Grasshopper', 'Grizzly', 'Groundhog', 'Hare',
  'Herring', 'Hippo', 'Horse', 'Ibis', 'Iguana',
  'Impala', 'Jellyfish', 'Kiwi', 'Kudu', 'Lorikeet',
  'Ladybug', 'Lemur', 'Llama', 'Lobster', 'Macaw',
  'Magpie', 'Manatee', 'Mandrill', 'Manta Ray', 'Meerkat',
  'Mink', 'Mole', 'Mongoose', 'Narwhal', 'Newt',
  'Nightingale', 'Ocelot', 'Okapi', 'Opossum', 'Orangutan',
  'Oryx', 'Ostrich', 'Pangolin', 'Pelican', 'Pheasant',
  'Pigeon', 'Platypus', 'Polar Bear', 'Porcupine', 'Porpoise',
  'Prairie Dog', 'Quail', 'Quokka', 'Reindeer', 'Rhinoceros',
  'Roadrunner', 'Rooster', 'Salamander', 'Salmon', 'Sea Horse',
  'Sea Lion', 'Sea Otter', 'Sea Turtle', 'Shark', 'Shrimp',
  'Skunk', 'Sloth', 'Snail', 'Starfish', 'Stingray',
  'Stork', 'Swallow', 'Tapir', 'Toad', 'Toucan',
  'Vole', 'Weasel', 'Wombat', 'Wren', 'Xerus',
  'Woodpecker', 'Yak', 'Bald Eagle', 'Blue Jay', 'Bunny',
  'Caribou', 'Catfish', 'Coyote', 'Crayfish', 'Dachshund',
  'Dalmatian', 'Eel', 'Egret', 'Flicker', 'Flounder',
  'Gull', 'Hermit Crab', 'Husky', 'Kingfisher', 'Kookaburra',
  'Lark', 'Mackerel', 'Marmoset', 'Moth', 'Muskrat',
  'Pronghorn', 'Sunbird', 'Tanager', 'Teal', 'Tern',
]
